### ISSUE TITLE
Add support for xp_redo

### ISSUE THREAD

**Issue by S-S-X** [pandorabox-io/spacecannon#10]
Add configurable XP limit for firing space cannon.
Related https://github.com/pandorabox-io/pandorabox_custom/issues/36

I think it would be best to add xp_redo as optional dependency with configurable XP limit, if configured limit is 0 then just disable functions completely, while performance impact would be minimal LuaJIT might actually be able to even reduce performance impact to zero when disabled (not sure about this, just what I would expect).

**Comment by BuckarooBanzay** [comment]
Extended the api-call:
```lua
spacecannon.can_shoot(pos, playername)
```

So we can override that in `pandorabox_custom` with whatever conditions we want
